---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 說明
在一個腳位上產生特定頻率的方波(占空比為50%)。可以指定一個時間長度，或是直到呼叫  link:../noTone[noTone()]為止。腳位可以連接到蜂鳴器或是喇叭來播放音調。

同一個時間只能產生一個音頻。若一個音頻正在別的腳位上播放，則呼叫tone()不會有其他作用。若是在同一個腳位上播放，則會再次設定頻率。

呼叫 `tone()` 方法時，也會介接腳位3與腳位11上的脈寬調變(PWM)輸出。

目前最低音頻為31Hz。如果想了解技術上的原因，可以參考 https://github.com/bhagman/Tone#ugly-details[Brett Hagman's notes]。
[%hardbreaks]


[float]
=== 語法
`tone(pin, frequency)`

`tone(pin, frequency, duration)`
[%hardbreaks]

[float]
=== 參數
`pin`: 欲產生音調的腳位。

`frequency`: 音調的頻率，單位為赫茲(Hertz)- `unsigned int`

`duration`: 播放音調的長度，單位為毫秒 (選擇性參數) - `unsigned long`
[%hardbreaks]

[float]
=== 回傳值
無

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 密技與警告
若你想在不同的腳位播放不同的音頻，必須先呼叫 `noTone()` 於當前腳位，再呼叫 `tone()` 於下一個腳位。
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Tone^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Pitch follower^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Simple Keyboard^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[multiple tones^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
